const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const keyInput=$('#print-key'),senderInput=$('#sender-name'),titleInput=$('#title'),messageInput=$('#message');
const receiptCanvas=$('#receipt-canvas'),receiptCtx=receiptCanvas.getContext('2d',{willReadFrequently:true});
const drawingCanvas=$('#drawing-canvas'),drawingCtx=drawingCanvas.getContext('2d');
const imageInput=$('#image-file'),sendButton=$('#send'),notice=$('#notice'),noticeIcon=$('#notice-icon'),noticeText=$('#notice-text');
let activePanel='compose',activeTemplate='',sourceImage=null,sourceImageUrl='',printerConnected=false,drawingUsed=false,renderTimer=0;
const MAX_IMAGE_BYTES=10*1024*1024;
const SIGNS=['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'];
const HOROSCOPES=[
  'A small surprise changes the rhythm of your day. Leave room for it.',
  'Finish one simple thing before beginning the ambitious one.',
  'A conversation becomes clearer when you ask the shortest question.',
  'Protect your attention. The quiet idea is the useful one today.',
  'Share the generous thought before you have time to edit it away.',
  'A practical choice brings more freedom than a perfect plan.',
  'Look again at something familiar. One detail has changed.',
  'Your instinct is good, but give the facts one last look.',
  'Take the longer route if it gives you a better story.',
  'A delayed answer is still an answer. Use the extra time well.',
  'Make something by hand today, even if it is only a tiny note.',
  'The day improves when you stop carrying a problem that is not yours.'
];
const SUDOKU=[
  [0,0,3,0,2,0,6,0,0],[9,0,0,3,0,5,0,0,1],[0,0,1,8,0,6,4,0,0],
  [0,0,8,1,0,2,9,0,0],[7,0,0,0,0,0,0,0,8],[0,0,6,7,0,8,2,0,0],
  [0,0,2,6,0,9,5,0,0],[8,0,0,2,0,3,0,0,9],[0,0,5,0,1,0,3,0,0]
];

function endpoint(){const value=keyInput.value.trim().replace(/\/+$/,'');const url=new URL(value);if(!/^https?:$/.test(url.protocol))throw new Error('invalid');return value}
function setNotice(state,text,icon=''){notice.className='notice '+state;noticeText.textContent=text;noticeIcon.textContent=icon;noticeIcon.hidden=!icon}
function errorText(error,action){if(error.message==='not-found')return'This Print Key was not found.';if(error.message==='offline')return'Little Printer is offline. Bring it online and try again.';if(error.message==='Failed to fetch')return'The browser could not reach the Print Key. Check HTTPS and CORS.';if(error.message==='invalid')return'Enter a valid Print Key URL.';return action==='connect'?'The server returned an invalid response.':'The receipt was not accepted by the server.'}
function receiptDate(){return new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'short',year:'numeric'}).format(new Date()).replace(',',' |').toUpperCase()}
function wrapLines(ctx,text,maxWidth){const paragraphs=String(text||'').split(/\n/),lines=[];for(const paragraph of paragraphs){if(!paragraph){lines.push('');continue}const words=paragraph.split(/\s+/);let line='';for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line)}return lines}
function drawCenteredLines(ctx,lines,y,lineHeight){for(const line of lines){ctx.fillText(line,192,y);y+=lineHeight}return y}
function hasPrintableContent(){if(activePanel==='draw')return drawingUsed;if(activePanel==='templates')return Boolean(activeTemplate);return Boolean(titleInput.value.trim()||messageInput.value.trim()||sourceImage)}
function updateSend(){sendButton.disabled=!senderInput.value.trim()||!hasPrintableContent()}
function scheduleRender(){clearTimeout(renderTimer);renderTimer=setTimeout(renderReceipt,45);updateSend()}

function ditherImage(image,targetWidth,maxHeight){const scale=Math.min(targetWidth/image.naturalWidth,maxHeight/image.naturalHeight,1);const w=Math.max(1,Math.round(image.naturalWidth*scale)),h=Math.max(1,Math.round(image.naturalHeight*scale));const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0,w,h);const data=ctx.getImageData(0,0,w,h),px=data.data,gray=new Float32Array(w*h);for(let i=0;i<gray.length;i++)gray[i]=px[i*4]*.299+px[i*4+1]*.587+px[i*4+2]*.114;const atkinson=$('#dither-mode').value==='atkinson';for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x,old=gray[i],next=old<128?0:255,error=(old-next)/8;gray[i]=next;if(atkinson){[[1,0],[2,0],[-1,1],[0,1],[1,1],[0,2]].forEach(([dx,dy])=>{const nx=x+dx,ny=y+dy;if(nx>=0&&nx<w&&ny<h)gray[ny*w+nx]+=error})}}for(let i=0;i<gray.length;i++){const value=gray[i]<128?0:255;px[i*4]=px[i*4+1]=px[i*4+2]=value;px[i*4+3]=255}ctx.putImageData(data,0,0);return canvas}

function drawHeader(ctx){ctx.fillStyle='#111';ctx.font='700 11px Arial';ctx.textAlign='center';ctx.fillText(receiptDate()+' | FROM '+(senderInput.value.trim()||'SENDER').toUpperCase(),192,22);ctx.setLineDash([5,4]);ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(20,38);ctx.lineTo(364,38);ctx.stroke();ctx.setLineDash([])}
function prepareCanvas(height){receiptCanvas.width=384;receiptCanvas.height=Math.max(220,Math.min(1400,Math.ceil(height)));receiptCtx.fillStyle='#fff';receiptCtx.fillRect(0,0,384,receiptCanvas.height);receiptCtx.fillStyle='#111';drawHeader(receiptCtx)}
function estimateComposeHeight(){let h=70;receiptCtx.font='700 40px Arial Narrow,Arial';h+=wrapLines(receiptCtx,titleInput.value.trim(),334).length*44;if(sourceImage)h+=Math.min(300,sourceImage.naturalHeight*(334/sourceImage.naturalWidth))+18;receiptCtx.font='24px Arial';h+=wrapLines(receiptCtx,messageInput.value.trim(),330).length*31;return Math.max(300,h+38)}
function renderCompose(){prepareCanvas(estimateComposeHeight());let y=67;const title=titleInput.value.trim(),body=messageInput.value.trim();if(title){receiptCtx.font='900 40px Arial Narrow,Arial';receiptCtx.textAlign='center';receiptCtx.textBaseline='top';y=drawCenteredLines(receiptCtx,wrapLines(receiptCtx,title.toUpperCase(),334),y,42)+8}if(sourceImage){const processed=ditherImage(sourceImage,334,300),x=(384-processed.width)/2;receiptCtx.drawImage(processed,x,y);y+=processed.height+18}if(body){receiptCtx.font='23px Arial';receiptCtx.textAlign='left';receiptCtx.textBaseline='top';for(const line of wrapLines(receiptCtx,body,330)){receiptCtx.fillText(line,27,y);y+=31}}if(!title&&!body&&!sourceImage){receiptCtx.fillStyle='#aaa';receiptCtx.font='900 46px Arial Narrow,Arial';receiptCtx.textAlign='center';receiptCtx.fillText('YOUR RECEIPT',192,155)}}
function renderDrawing(){prepareCanvas(390);receiptCtx.drawImage(drawingCanvas,0,55,384,300);receiptCtx.font='900 19px Arial';receiptCtx.textAlign='center';receiptCtx.fillText('QUICKDRAW',192,372)}
function drawLeaf(ctx,x,y,scale,angle){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.scale(scale,scale);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,55);ctx.quadraticCurveTo(-38,0,0,-60);ctx.quadraticCurveTo(38,0,0,55);ctx.stroke();ctx.beginPath();ctx.moveTo(0,55);ctx.lineTo(0,-55);ctx.stroke();for(let i=-35;i<=30;i+=16){ctx.beginPath();ctx.moveTo(0,i);ctx.lineTo(i<0?-23:23,i-13);ctx.stroke()}ctx.restore()}
function renderHerbarium(){const plant=$('#plant-name')?.value.trim()||'Wild specimen',place=$('#plant-place')?.value.trim()||'Found nearby';prepareCanvas(540);receiptCtx.textAlign='center';receiptCtx.font='900 45px Arial Narrow,Arial';receiptCtx.fillText('HERBARIUM',192,89);receiptCtx.font='italic 18px Georgia';receiptCtx.fillText(plant,192,121);receiptCtx.save();receiptCtx.translate(192,310);receiptCtx.lineWidth=3;receiptCtx.beginPath();receiptCtx.moveTo(0,120);receiptCtx.quadraticCurveTo(-18,0,10,-140);receiptCtx.stroke();drawLeaf(receiptCtx,-28,65,.9,-.45);drawLeaf(receiptCtx,28,2,.76,.55);drawLeaf(receiptCtx,-20,-62,.6,-.5);receiptCtx.restore();receiptCtx.font='700 12px Arial';receiptCtx.fillText(place.toUpperCase(),192,485);receiptCtx.font='11px Arial';receiptCtx.fillText(new Intl.DateTimeFormat('en-GB',{dateStyle:'long'}).format(new Date()).toUpperCase(),192,506)}
function renderHoroscope(){const sign=$('#zodiac-sign')?.value||'Aries',day=Math.floor(Date.now()/86400000),message=HOROSCOPES[(day+SIGNS.indexOf(sign))%HOROSCOPES.length];prepareCanvas(500);receiptCtx.textAlign='center';receiptCtx.font='900 38px Arial Narrow,Arial';receiptCtx.fillText('DAILY HOROSCOPE',192,88);receiptCtx.font='900 54px Arial Narrow,Arial';receiptCtx.fillText(sign.toUpperCase(),192,148);receiptCtx.beginPath();receiptCtx.arc(192,223,45,0,Math.PI*2);receiptCtx.lineWidth=3;receiptCtx.stroke();receiptCtx.font='700 36px Georgia';receiptCtx.fillText(SIGNS.indexOf(sign)+1,192,236);receiptCtx.font='21px Georgia';let y=305;for(const line of wrapLines(receiptCtx,message,315)){receiptCtx.fillText(line,192,y);y+=29}receiptCtx.font='700 11px Arial';receiptCtx.fillText('FOR ENTERTAINMENT · '+new Date().toLocaleDateString('en-GB'),192,460)}
function renderSudoku(){prepareCanvas(570);receiptCtx.textAlign='center';receiptCtx.font='900 48px Arial Narrow,Arial';receiptCtx.fillText('DAILY SUDOKU',192,91);receiptCtx.font='12px Arial';receiptCtx.fillText('A QUIET PUZZLE FOR YOUR COFFEE',192,116);const size=315,cell=35,left=(384-size)/2,top=145;receiptCtx.textBaseline='middle';receiptCtx.font='700 18px Arial';for(let i=0;i<=9;i++){receiptCtx.lineWidth=i%3===0?3:1;receiptCtx.beginPath();receiptCtx.moveTo(left+i*cell,top);receiptCtx.lineTo(left+i*cell,top+size);receiptCtx.stroke();receiptCtx.beginPath();receiptCtx.moveTo(left,top+i*cell);receiptCtx.lineTo(left+size,top+i*cell);receiptCtx.stroke()}for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(SUDOKU[r][c])receiptCtx.fillText(String(SUDOKU[r][c]),left+c*cell+cell/2,top+r*cell+cell/2+1);receiptCtx.textBaseline='alphabetic';receiptCtx.font='11px Arial';receiptCtx.fillText('LEVEL: GENTLE · NO PEEKING',192,500)}
function seededRandom(seed){let value=seed%2147483647;return()=>((value=value*16807%2147483647)-1)/2147483646}
function renderMaze(){prepareCanvas(570);receiptCtx.textAlign='center';receiptCtx.font='900 50px Arial Narrow,Arial';receiptCtx.fillText('DAILY MAZE',192,92);receiptCtx.font='12px Arial';receiptCtx.fillText('START AT THE TOP · ESCAPE AT THE BOTTOM',192,116);const cols=15,rows=15,cell=21,left=(384-cols*cell)/2,top=145,rnd=seededRandom(Math.floor(Date.now()/86400000)),seen=Array.from({length:rows},()=>Array(cols).fill(false)),walls=Array.from({length:rows},()=>Array.from({length:cols},()=>[1,1,1,1]));function carve(x,y){seen[y][x]=true;const dirs=[[0,-1,0,2],[1,0,1,3],[0,1,2,0],[-1,0,3,1]].sort(()=>rnd()-.5);for(const[dX,dY,wall,opposite]of dirs){const nx=x+dX,ny=y+dY;if(nx>=0&&nx<cols&&ny>=0&&ny<rows&&!seen[ny][nx]){walls[y][x][wall]=0;walls[ny][nx][opposite]=0;carve(nx,ny)}}}carve(0,0);walls[0][0][0]=0;walls[rows-1][cols-1][2]=0;receiptCtx.lineWidth=2;for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const px=left+x*cell,py=top+y*cell,w=walls[y][x];if(w[0]){receiptCtx.beginPath();receiptCtx.moveTo(px,py);receiptCtx.lineTo(px+cell,py);receiptCtx.stroke()}if(w[1]){receiptCtx.beginPath();receiptCtx.moveTo(px+cell,py);receiptCtx.lineTo(px+cell,py+cell);receiptCtx.stroke()}if(w[2]){receiptCtx.beginPath();receiptCtx.moveTo(px,py+cell);receiptCtx.lineTo(px+cell,py+cell);receiptCtx.stroke()}if(w[3]){receiptCtx.beginPath();receiptCtx.moveTo(px,py);receiptCtx.lineTo(px,py+cell);receiptCtx.stroke()}}receiptCtx.font='11px Arial';receiptCtx.fillText('A NEW MAZE EVERY DAY',192,500)}
function renderWeather(){const city=$('#weather-city')?.value.trim()||'Home',temperature=$('#weather-temp')?.value||'18',condition=$('#weather-condition')?.value||'Cloudy';prepareCanvas(500);receiptCtx.textAlign='center';receiptCtx.font='900 42px Arial Narrow,Arial';receiptCtx.fillText(city.toUpperCase(),192,90);receiptCtx.font='900 92px Arial Narrow,Arial';receiptCtx.fillText(temperature+'°',192,205);receiptCtx.lineWidth=5;if(condition==='Sunny'){receiptCtx.beginPath();receiptCtx.arc(192,285,38,0,Math.PI*2);receiptCtx.stroke();for(let i=0;i<8;i++){const a=i*Math.PI/4;receiptCtx.beginPath();receiptCtx.moveTo(192+55*Math.cos(a),285+55*Math.sin(a));receiptCtx.lineTo(192+74*Math.cos(a),285+74*Math.sin(a));receiptCtx.stroke()}}else{receiptCtx.beginPath();receiptCtx.arc(165,286,33,Math.PI,Math.PI*2);receiptCtx.arc(207,276,44,Math.PI,Math.PI*2);receiptCtx.lineTo(250,320);receiptCtx.lineTo(133,320);receiptCtx.closePath();receiptCtx.stroke()}receiptCtx.font='900 30px Arial Narrow,Arial';receiptCtx.fillText(condition.toUpperCase(),192,385);receiptCtx.font='12px Arial';receiptCtx.fillText('MANUAL FORECAST · SERVER DATA COMING LATER',192,430)}
function renderAgenda(){const date=new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long'}).format(new Date()),items=[$('#agenda-1')?.value,$('#agenda-2')?.value,$('#agenda-3')?.value].filter(Boolean);prepareCanvas(520);receiptCtx.textAlign='center';receiptCtx.font='900 45px Arial Narrow,Arial';receiptCtx.fillText('TODAY',192,88);receiptCtx.font='700 15px Arial';receiptCtx.fillText(date.toUpperCase(),192,116);receiptCtx.textAlign='left';receiptCtx.font='20px Arial';let y=175;(items.length?items:['First important thing','A small useful task','Something just for you']).forEach((item,index)=>{receiptCtx.strokeRect(36,y-17,20,20);receiptCtx.fillText(item,72,y);if(index<2){receiptCtx.setLineDash([3,4]);receiptCtx.beginPath();receiptCtx.moveTo(36,y+28);receiptCtx.lineTo(348,y+28);receiptCtx.stroke();receiptCtx.setLineDash([])}y+=92});receiptCtx.textAlign='center';receiptCtx.font='11px Arial';receiptCtx.fillText('ONE DAY · THREE GOOD THINGS',192,475)}
function renderNote(){const text=$('#classic-note')?.value.trim()||'HELLO FROM LITTLE PRINTER';prepareCanvas(430);receiptCtx.textAlign='center';receiptCtx.textBaseline='middle';let size=68;do{receiptCtx.font='900 '+size+'px Arial Narrow,Arial';if(wrapLines(receiptCtx,text.toUpperCase(),330).length<=5)break;size-=4}while(size>34);const lines=wrapLines(receiptCtx,text.toUpperCase(),330),lineHeight=size*.88,start=225-(lines.length*lineHeight)/2;for(let i=0;i<lines.length;i++)receiptCtx.fillText(lines[i],192,start+i*lineHeight)}
function renderTemplate(){if(activeTemplate==='herbarium')renderHerbarium();else if(activeTemplate==='horoscope')renderHoroscope();else if(activeTemplate==='sudoku')renderSudoku();else if(activeTemplate==='maze')renderMaze();else if(activeTemplate==='weather')renderWeather();else if(activeTemplate==='agenda')renderAgenda();else renderNote()}
function renderReceipt(){if(activePanel==='draw')renderDrawing();else if(activePanel==='templates'&&activeTemplate)renderTemplate();else renderCompose();$('#receipt-length').textContent='≈ '+Math.ceil(receiptCanvas.height/8)+' mm receipt';updateSend()}

function selectPanel(panel){activePanel=panel;$$('.studio-tabs button').forEach(button=>button.classList.toggle('active',button.dataset.panel===panel));$$('.studio-panel').forEach(section=>{section.hidden=section.id!=='panel-'+panel;section.classList.toggle('active',!section.hidden)});scheduleRender()}
function templateFields(name){if(name==='herbarium')return'<label>SPECIMEN<input id="plant-name" maxlength="40" value="Wild specimen"></label><label>FOUND AT<input id="plant-place" maxlength="50" value="Found nearby"></label>';if(name==='horoscope')return'<label class="wide">ZODIAC SIGN<select id="zodiac-sign">'+SIGNS.map(sign=>'<option>'+sign+'</option>').join('')+'</select></label>';if(name==='sudoku')return'<p class="wide template-copy">A printable daily 9×9 puzzle inspired by the original publication.</p>';if(name==='maze')return'<p class="wide template-copy">A deterministic maze that changes automatically every day.</p>';if(name==='weather')return'<label>CITY<input id="weather-city" maxlength="30" value="Bologna"></label><label>TEMPERATURE<input id="weather-temp" type="number" min="-50" max="60" value="18"></label><label class="wide">CONDITION<select id="weather-condition"><option>Cloudy</option><option>Sunny</option><option>Rainy</option></select></label>';if(name==='agenda')return'<label class="wide">ITEM 1<input id="agenda-1" maxlength="42" value="First important thing"></label><label class="wide">ITEM 2<input id="agenda-2" maxlength="42" value="A small useful task"></label><label class="wide">ITEM 3<input id="agenda-3" maxlength="42" value="Something just for you"></label>';return'<label class="wide">POSTER MESSAGE<input id="classic-note" maxlength="120" value="Hello from Little Printer"></label>'}
function chooseTemplate(name){activeTemplate=name;$$('[data-template]').forEach(button=>button.classList.toggle('active',button.dataset.template===name));$('#template-options').innerHTML=templateFields(name);$('#template-options').querySelectorAll('input,select').forEach(control=>control.addEventListener('input',scheduleRender));scheduleRender()}

async function checkPrinter(){let url;try{url=endpoint()}catch(error){setNotice('error',errorText(error,'connect'),'×');return}const connect=$('#connect');connect.disabled=true;$('#refresh-status').disabled=true;connect.textContent='…';setNotice('sending','Looking for your Little Printer…','⌛');try{const response=await fetch(url,{method:'GET',mode:'cors',cache:'no-store',headers:{Accept:'application/json'}});if(response.status===404)throw new Error('not-found');if(!response.ok)throw new Error('HTTP '+response.status);const info=await response.json();if(!info?.name||!info?.status)throw new Error('invalid-response');printerConnected=true;$('#printer-name').textContent=info.name;const safeStatus=String(info.status).replace(/[^a-z-]/gi,'');$('#printer-info').innerHTML='<span class="dot '+safeStatus+'"></span>'+info.status+' · @'+String(info.owner||'unknown').replace(/[<>&"']/g,'')+' · checked now';setNotice(info.status==='online'?'sent':'error',info.status==='online'?'Your printer is online and ready.':'Your printer is currently offline.',info.status==='online'?'✓':'×')}catch(error){printerConnected=false;setNotice('error',errorText(error,'connect'),'×')}finally{connect.disabled=false;$('#refresh-status').disabled=false;connect.textContent='CONNECT'}}
function canvasBlob(){return new Promise((resolve,reject)=>receiptCanvas.toBlob(blob=>blob?resolve(blob):reject(new Error('render')),'image/png'))}
async function sendReceipt(){if(!senderInput.value.trim()){setNotice('error','Enter your name before sending.','×');return}if(!hasPrintableContent()){setNotice('error','Create something to print first.','×');return}let url;try{url=new URL(endpoint());url.searchParams.set('from',senderInput.value.trim())}catch(error){setNotice('error','Connect a valid Print Key first.','×');return}sendButton.disabled=true;setNotice('sending','Sending the exact thermal receipt…','⌛');try{renderReceipt();const blob=await canvasBlob(),response=await fetch(url.toString(),{method:'POST',mode:'cors',cache:'no-store',headers:{'Content-Type':'image/png',Accept:'application/json'},body:blob}),result=await response.json().catch(()=>null);if(response.status===504||result?.status==='failed-offline')throw new Error('offline');if(response.status===404)throw new Error('not-found');if(!response.ok||result?.status!=='sent')throw new Error('HTTP '+response.status);setNotice('sent','Receipt sent to Little Printer!','✓');setTimeout(checkPrinter,800)}catch(error){setNotice('error',errorText(error,'send'),'×')}finally{updateSend()}}

function scheduledJobs(){try{return JSON.parse(localStorage.getItem('lp-scheduled-jobs')||'[]')}catch{return[]}}
function renderJobs(){const jobs=scheduledJobs(),list=$('#scheduled-list');list.innerHTML=jobs.length?jobs.map(job=>'<div class="scheduled-item"><span><b>'+new Date(job.executeAt).toLocaleString()+'</b><br>'+job.kind+' · waiting for server connector</span><button type="button" data-delete-job="'+job.id+'">DELETE</button></div>').join(''):'<div class="scheduled-item"><span>No scheduled prints.</span></div>';list.querySelectorAll('[data-delete-job]').forEach(button=>button.addEventListener('click',()=>{localStorage.setItem('lp-scheduled-jobs',JSON.stringify(scheduledJobs().filter(job=>job.id!==button.dataset.deleteJob)));renderJobs()}))}
async function saveSchedule(){const executeAt=$('#schedule-time').value;if(!executeAt||new Date(executeAt)<=new Date()){setNotice('error','Choose a future date and time.','×');return}if(!senderInput.value.trim()||!hasPrintableContent()){setNotice('error','Add your name and printable content first.','×');return}renderReceipt();const jobs=scheduledJobs();if(jobs.length>=8){setNotice('error','The local queue can contain up to 8 prints.','×');return}jobs.push({version:1,id:String(Date.now()),executeAt:new Date(executeAt).toISOString(),createdAt:new Date().toISOString(),sender:senderInput.value.trim(),kind:activePanel==='templates'?activeTemplate:activePanel,receiptPng:receiptCanvas.toDataURL('image/png'),requiresServerConnector:true});try{localStorage.setItem('lp-scheduled-jobs',JSON.stringify(jobs));renderJobs();setNotice('sent','Print saved in the local schedule. It will be activated when the server connector is added.','✓')}catch{setNotice('error','This receipt is too large for local scheduling. Remove the image and try again.','×')}}

function setupDrawing(){drawingCtx.fillStyle='#fff';drawingCtx.fillRect(0,0,384,300);drawingCtx.strokeStyle='#111';drawingCtx.lineCap='round';drawingCtx.lineJoin='round';let drawing=false,last=null;const point=event=>{const rect=drawingCanvas.getBoundingClientRect(),touch=event.touches?.[0];return{x:((touch?.clientX??event.clientX)-rect.left)*(384/rect.width),y:((touch?.clientY??event.clientY)-rect.top)*(300/rect.height)}};const start=event=>{event.preventDefault();drawing=true;last=point(event)};const move=event=>{if(!drawing)return;event.preventDefault();const next=point(event);drawingCtx.lineWidth=Number($('#brush-size').value);drawingCtx.beginPath();drawingCtx.moveTo(last.x,last.y);drawingCtx.lineTo(next.x,next.y);drawingCtx.stroke();last=next;drawingUsed=true;scheduleRender()};const end=()=>{drawing=false;last=null};drawingCanvas.addEventListener('pointerdown',start);drawingCanvas.addEventListener('pointermove',move);window.addEventListener('pointerup',end);$('#clear-drawing').addEventListener('click',()=>{drawingCtx.fillStyle='#fff';drawingCtx.fillRect(0,0,384,300);drawingUsed=false;scheduleRender()})}

$('#reveal').addEventListener('click',event=>{const show=keyInput.type==='password';keyInput.type=show?'url':'password';event.currentTarget.textContent=show?'HIDE':'SHOW'});
$('#connect').addEventListener('click',checkPrinter);$('#refresh-status').addEventListener('click',checkPrinter);
keyInput.addEventListener('input',()=>{printerConnected=false;$('#printer-name').textContent='Connect a printer';$('#printer-info').textContent='Enter your Nord Projects Print Key';setNotice('','Connect with a Print Key, create a receipt, then send it.')});
senderInput.addEventListener('input',scheduleRender);titleInput.addEventListener('input',scheduleRender);messageInput.addEventListener('input',()=>{const chars=messageInput.value.length,lines=messageInput.value?messageInput.value.split(/\n/).reduce((sum,line)=>sum+Math.max(1,Math.ceil(line.length/38)),0):0;$('#counter').textContent=chars+'/800 characters';$('#line-count').textContent=lines+' estimated '+(lines===1?'line':'lines');scheduleRender()});
$$('.studio-tabs button').forEach(button=>button.addEventListener('click',()=>selectPanel(button.dataset.panel)));$$('[data-template]').forEach(button=>button.addEventListener('click',()=>chooseTemplate(button.dataset.template)));
imageInput.addEventListener('change',()=>{const file=imageInput.files?.[0];if(sourceImageUrl)URL.revokeObjectURL(sourceImageUrl);sourceImage=null;sourceImageUrl='';if(!file){scheduleRender();return}if(!['image/png','image/jpeg','image/gif'].includes(file.type)||file.size>MAX_IMAGE_BYTES){imageInput.value='';setNotice('error',file.size>MAX_IMAGE_BYTES?'The image must be smaller than 10 MB.':'Choose a PNG, JPEG or GIF image.','×');return}sourceImageUrl=URL.createObjectURL(file);const image=new Image();image.onload=()=>{sourceImage=image;$('#image-file-name').textContent=file.name;$('#remove-image').hidden=false;setNotice('','Image added. Preview converted to real 1-bit thermal output.');scheduleRender()};image.src=sourceImageUrl});
$('#remove-image').addEventListener('click',()=>{if(sourceImageUrl)URL.revokeObjectURL(sourceImageUrl);sourceImage=null;sourceImageUrl='';imageInput.value='';$('#image-file-name').textContent='＋ Add PNG, JPEG or GIF';$('#remove-image').hidden=true;scheduleRender()});$('#dither-mode').addEventListener('change',scheduleRender);
sendButton.addEventListener('click',sendReceipt);$('#schedule-open').addEventListener('click',()=>{$('#scheduler').hidden=!$('#scheduler').hidden;renderJobs()});$('#schedule-save').addEventListener('click',saveSchedule);
setupDrawing();chooseTemplate('herbarium');selectPanel('compose');const defaultSchedule=new Date(Date.now()+3600000);defaultSchedule.setMinutes(defaultSchedule.getMinutes()-defaultSchedule.getTimezoneOffset());$('#schedule-time').min=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);$('#schedule-time').value=defaultSchedule.toISOString().slice(0,16);document.fonts?.ready.then(renderReceipt);renderReceipt();renderJobs();
