const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const keyInput=$('#print-key'),senderInput=$('#sender-name'),titleInput=$('#title'),messageInput=$('#message');
const receiptCanvas=$('#receipt-canvas'),receiptCtx=receiptCanvas.getContext('2d',{willReadFrequently:true});
const drawingCanvas=$('#drawing-canvas'),drawingCtx=drawingCanvas.getContext('2d');
const imageInput=$('#image-file'),sendButton=$('#send'),notice=$('#notice'),noticeIcon=$('#notice-icon'),noticeText=$('#notice-text');
let activePanel='compose',sourceImage=null,sourceImageUrl='',printerConnected=false,drawingUsed=false,renderTimer=0,showPrintHeader=true;
const MAX_IMAGE_BYTES=10*1024*1024;
const MAX_PHOTO_HEIGHT=11000,MAX_RECEIPT_HEIGHT=12000;
const REMOVED_PRINT_HEADER_HEIGHT=47;
const SUDOKU=[
  [0,0,3,0,2,0,6,0,0],[9,0,0,3,0,5,0,0,1],[0,0,1,8,0,6,4,0,0],
  [0,0,8,1,0,2,9,0,0],[7,0,0,0,0,0,0,0,8],[0,0,6,7,0,8,2,0,0],
  [0,0,2,6,0,9,5,0,0],[8,0,0,2,0,3,0,0,9],[0,0,5,0,1,0,3,0,0]
];
const SUDOKU_SOLUTION=[
  [4,8,3,9,2,1,6,5,7],[9,6,7,3,4,5,8,2,1],[2,5,1,8,7,6,4,9,3],
  [5,4,8,1,3,2,9,7,6],[7,2,9,5,6,4,1,3,8],[1,3,6,7,9,8,2,4,5],
  [3,7,2,6,8,9,5,1,4],[8,1,4,2,5,3,7,6,9],[6,9,5,4,1,7,3,8,2]
];
const BUTTERFLIES={
  'Peacock':['Aglais io','Dark eyespots flash like a warning when the wings open.'],
  'Brimstone':['Gonepteryx rhamni','One of Britain’s longest-lived butterflies; adults can overwinter.'],
  'Small Tortoiseshell':['Aglais urticae','A familiar garden visitor whose caterpillars feed on nettles.']
};
const FRUITS={
  'Pomegranate':['Punica granatum','A leathery berry divided into chambers packed with jewel-like arils.'],
  'Physalis':['Physalis peruviana','The berry ripens inside a papery calyx that forms a natural lantern.'],
  'Dragon fruit':['Selenicereus undatus','A climbing cactus fruit filled with hundreds of tiny black seeds.']
};
const POLLEN={
  'Sunflower':['Helianthus annuus','Spiny grains designed to cling to visiting pollinators.'],
  'Lily':['Lilium','Large oval grains with a finely netted outer wall.'],
  'Pine':['Pinus','Two air sacs help each grain travel on the wind.']
};
const GLYPHS={
  '&':['AMPERSAND','Developed from a ligature of the Latin letters E and T: et, meaning “and”.'],
  '¶':['PILCROW','A paragraph mark descended from the letter C for the Latin capitulum.'],
  '‽':['INTERROBANG','A modern glyph combining the question mark and exclamation point.']
};
const mazeHeader=new Image(),mazeFooter=new Image();
mazeHeader.src='assets/maze-a-day-header.png';mazeFooter.src='assets/maze-a-day-footer.png';

function endpoint(){const value=keyInput.value.trim().replace(/\/+$/,'');const url=new URL(value);if(!/^https?:$/.test(url.protocol))throw new Error('invalid');return value}
function setNotice(state,text,icon=''){notice.className='notice '+state;noticeText.textContent=text;noticeIcon.textContent=icon;noticeIcon.hidden=!icon}
function errorText(error,action){if(error.message==='not-found')return'This Print Key was not found.';if(error.message==='offline')return'Little Printer is offline. Bring it online and try again.';if(error.message==='Failed to fetch')return'The browser could not reach the Print Key. Check HTTPS and CORS.';if(error.message==='invalid')return'Enter a valid Print Key URL.';return action==='connect'?'The server returned an invalid response.':'The receipt was not accepted by the server.'}
function printHeaderText(){const now=new Date(),time=new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false}).format(now),parts=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).formatToParts(now).filter(part=>part.type!=='literal').map(part=>[part.type,part.value]));return time+' | '+parts.day+'-'+parts.month.toUpperCase()+'-'+parts.year+' | '+(senderInput.value.trim()||'SENDER').toUpperCase()}
function wrapLines(ctx,text,maxWidth){const paragraphs=String(text||'').split(/\n/),lines=[];for(const paragraph of paragraphs){if(!paragraph){lines.push('');continue}const words=paragraph.split(/\s+/);let line='';for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line)}return lines}
function drawCenteredLines(ctx,lines,y,lineHeight){for(const line of lines){ctx.fillText(line,192,y);y+=lineHeight}return y}
function hasPrintableContent(){if(activePanel==='draw')return drawingUsed;return Boolean(titleInput.value.trim()||messageInput.value.trim()||sourceImage)}
function updateSend(){sendButton.disabled=!senderInput.value.trim()||!hasPrintableContent()}
function scheduleRender(){clearTimeout(renderTimer);renderTimer=setTimeout(renderReceipt,45);updateSend()}

function ditherImage(image,targetWidth,maxHeight){const scale=Math.min(targetWidth/image.naturalWidth,maxHeight/image.naturalHeight),w=Math.max(1,Math.round(image.naturalWidth*scale)),h=Math.max(1,Math.round(image.naturalHeight*scale)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(image,0,0,w,h);const data=ctx.getImageData(0,0,w,h),px=data.data,gray=new Float32Array(w*h),hist=new Uint32Array(256);for(let i=0;i<gray.length;i++){const value=Math.round(px[i*4]*.299+px[i*4+1]*.587+px[i*4+2]*.114);gray[i]=value;hist[value]++}const cutoff=gray.length*.015;let low=0,high=255,total=0;for(;low<255&&total+hist[low]<cutoff;low++)total+=hist[low];total=0;for(;high>0&&total+hist[high]<cutoff;high--)total+=hist[high];if(high-low>35)for(let i=0;i<gray.length;i++)gray[i]=Math.max(0,Math.min(255,(gray[i]-low)*255/(high-low)));const mode=$('#dither-mode').value,spread=(x,y,error,weights)=>weights.forEach(([dx,dy,factor])=>{const nx=x+dx,ny=y+dy;if(nx>=0&&nx<w&&ny>=0&&ny<h)gray[ny*w+nx]+=error*factor});for(let y=0;y<h;y++){const reverse=mode==='photo-hq'&&y%2===1,start=reverse?w-1:0,end=reverse?-1:w,step=reverse?-1:1;for(let x=start;x!==end;x+=step){const i=y*w+x,old=gray[i],next=old<128?0:255,error=old-next;gray[i]=next;if(mode==='atkinson')spread(x,y,error,[[1,0,1/8],[2,0,1/8],[-1,1,1/8],[0,1,1/8],[1,1,1/8],[0,2,1/8]]);else if(mode==='photo-hq'){const dir=reverse?-1:1;spread(x,y,error,[[dir,0,7/16],[-dir,1,3/16],[0,1,5/16],[dir,1,1/16]])}}}for(let i=0;i<gray.length;i++){const value=gray[i]<128?0:255;px[i*4]=px[i*4+1]=px[i*4+2]=value;px[i*4+3]=255}ctx.putImageData(data,0,0);return canvas}

function drawPrintHeader(ctx){const text=printHeaderText();let size=16;ctx.textAlign='center';ctx.textBaseline='top';do{ctx.font='900 '+size+'px Arial Black,Arial,sans-serif';size--}while(ctx.measureText(text).width>364&&size>=9);ctx.fillStyle='#111';ctx.fillText(text,192,8)}
function scaledImageSize(image,targetWidth,maxHeight){const scale=Math.min(targetWidth/image.naturalWidth,maxHeight/image.naturalHeight);return{width:Math.max(1,Math.round(image.naturalWidth*scale)),height:Math.max(1,Math.round(image.naturalHeight*scale))}}
function prepareCanvas(height){const removedHeight=showPrintHeader?0:REMOVED_PRINT_HEADER_HEIGHT;receiptCanvas.width=384;receiptCanvas.height=Math.max(220,Math.min(MAX_RECEIPT_HEIGHT,Math.ceil(height-removedHeight)));receiptCtx.fillStyle='#fff';receiptCtx.fillRect(0,0,384,receiptCanvas.height);receiptCtx.fillStyle='#111';if(showPrintHeader)drawPrintHeader(receiptCtx);else receiptCtx.translate(0,-REMOVED_PRINT_HEADER_HEIGHT)}
function estimateComposeHeight(){let h=70;receiptCtx.font='700 40px Arial Narrow,Arial';h+=wrapLines(receiptCtx,titleInput.value.trim(),334).length*44;if(sourceImage)h+=scaledImageSize(sourceImage,334,MAX_PHOTO_HEIGHT).height+18;receiptCtx.font='24px Arial';h+=wrapLines(receiptCtx,messageInput.value.trim(),330).length*31;return Math.max(300,h+38)}
function renderCompose(){prepareCanvas(estimateComposeHeight());let y=67;const title=titleInput.value.trim(),body=messageInput.value.trim();if(title){receiptCtx.font='900 40px Arial Narrow,Arial';receiptCtx.textAlign='center';receiptCtx.textBaseline='top';y=drawCenteredLines(receiptCtx,wrapLines(receiptCtx,title.toUpperCase(),334),y,42)+8}if(sourceImage){const processed=ditherImage(sourceImage,334,MAX_PHOTO_HEIGHT),x=(384-processed.width)/2;receiptCtx.drawImage(processed,x,y);y+=processed.height+18}if(body){receiptCtx.font='23px Arial';receiptCtx.textAlign='left';receiptCtx.textBaseline='top';for(const line of wrapLines(receiptCtx,body,330)){receiptCtx.fillText(line,27,y);y+=31}}if(!title&&!body&&!sourceImage){receiptCtx.fillStyle='#aaa';receiptCtx.font='900 46px Arial Narrow,Arial';receiptCtx.textAlign='center';receiptCtx.fillText('YOUR RECEIPT',192,155)}}
function renderDrawing(){prepareCanvas(390);receiptCtx.drawImage(drawingCanvas,0,55,384,300);receiptCtx.font='900 19px Arial';receiptCtx.textAlign='center';receiptCtx.fillText('QUICKDRAW',192,372)}
function archiveFooter(){}
function dailyPuzzle(){const difficulty=$('#puzzle-level')?.value||'Medium',grid=SUDOKU.map(row=>row.slice()),day=Math.floor(Date.now()/86400000),rnd=seededRandom(day+137),cells=[];for(let r=0;r<9;r++)for(let c=0;c<9;c++)cells.push([r,c]);cells.sort(()=>rnd()-.5);if(difficulty==='Easy'){let added=0;for(const[r,c]of cells)if(!grid[r][c]&&added++<12)grid[r][c]=SUDOKU_SOLUTION[r][c]}if(difficulty==='Hard'){let removed=0;for(const[r,c]of cells)if(grid[r][c]&&removed++<9)grid[r][c]=0}const shift=day%9;return{difficulty,grid:grid.map(row=>row.map(value=>value?((value+shift-1)%9)+1:0))}}
function renderDailyPuzzle(){const puzzle=dailyPuzzle();prepareCanvas(545);receiptCtx.textAlign='center';receiptCtx.font='900 48px Arial Narrow,Arial';receiptCtx.fillText('DAILY PUZZLE',192,91);receiptCtx.font='12px Arial';receiptCtx.fillText('A NEW SUDOKU FOR TODAY',192,116);const size=315,cell=35,left=(384-size)/2,top=145;receiptCtx.textBaseline='middle';receiptCtx.font='700 18px Arial';for(let i=0;i<=9;i++){receiptCtx.lineWidth=i%3===0?3:1;receiptCtx.beginPath();receiptCtx.moveTo(left+i*cell,top);receiptCtx.lineTo(left+i*cell,top+size);receiptCtx.stroke();receiptCtx.beginPath();receiptCtx.moveTo(left,top+i*cell);receiptCtx.lineTo(left+size,top+i*cell);receiptCtx.stroke()}for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(puzzle.grid[r][c])receiptCtx.fillText(String(puzzle.grid[r][c]),left+c*cell+cell/2,top+r*cell+cell/2+1);receiptCtx.textBaseline='alphabetic';receiptCtx.font='11px Arial';receiptCtx.fillText('LEVEL: '+puzzle.difficulty.toUpperCase()+' · '+new Date().toLocaleDateString('en-GB'),192,500)}
function seededRandom(seed){let value=seed%2147483647;return()=>((value=value*16807%2147483647)-1)/2147483646}
function renderMaze(){const choice=$('#maze-size')?.value||'Medium',sizes={Small:[9,12,26],Medium:[13,17,20],Large:[19,25,14]},[cols,rows,cell]=sizes[choice],height=rows*cell+165;prepareCanvas(height);if(mazeHeader.complete&&mazeHeader.naturalWidth)receiptCtx.drawImage(mazeHeader,10,56,364,37);else{receiptCtx.textAlign='center';receiptCtx.font='900 42px Arial Narrow,Arial';receiptCtx.fillText('MAZE-A-DAY',192,88)}const left=(384-cols*cell)/2,top=110,rnd=seededRandom(Math.floor(Date.now()/86400000)+cols),seen=Array.from({length:rows},()=>Array(cols).fill(false)),walls=Array.from({length:rows},()=>Array.from({length:cols},()=>[1,1,1,1]));function carve(x,y){seen[y][x]=true;const dirs=[[0,-1,0,2],[1,0,1,3],[0,1,2,0],[-1,0,3,1]].sort(()=>rnd()-.5);for(const[dx,dy,wall,opposite]of dirs){const nx=x+dx,ny=y+dy;if(nx>=0&&nx<cols&&ny>=0&&ny<rows&&!seen[ny][nx]){walls[y][x][wall]=0;walls[ny][nx][opposite]=0;carve(nx,ny)}}}carve(0,0);walls[0][0][0]=0;walls[rows-1][cols-1][2]=0;receiptCtx.lineWidth=1.6;for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const px=left+x*cell,py=top+y*cell,w=walls[y][x];[[w[0],px,py,px+cell,py],[w[1],px+cell,py,px+cell,py+cell],[w[2],px,py+cell,px+cell,py+cell],[w[3],px,py,px,py+cell]].forEach(([on,x1,y1,x2,y2])=>{if(on){receiptCtx.beginPath();receiptCtx.moveTo(x1,y1);receiptCtx.lineTo(x2,y2);receiptCtx.stroke()}})}receiptCtx.fillStyle='#111';for(let i=0;i<5;i++){const gx=Math.floor(rnd()*cols),gy=Math.floor(rnd()*rows);receiptCtx.beginPath();receiptCtx.arc(left+(gx+.5)*cell,top+(gy+.5)*cell,Math.max(2,cell*.16),0,Math.PI*2);receiptCtx.fill()}const fy=top+rows*cell+13;if(mazeFooter.complete&&mazeFooter.naturalWidth)receiptCtx.drawImage(mazeFooter,10,fy,364,16);else{receiptCtx.textAlign='center';receiptCtx.font='9px Arial';receiptCtx.fillText('A NEW MAZE EVERY DAY',192,fy+10)}archiveFooter('ORIGINAL MAZE-A-DAY CODE · MIT · NICHOLAS O’LEARY')}
function renderWeather(){const city=$('#weather-city')?.value.trim()||'Home',temperature=$('#weather-temp')?.value||'18',condition=$('#weather-condition')?.value||'Cloudy';prepareCanvas(500);receiptCtx.textAlign='center';receiptCtx.font='900 25px Arial Narrow,Arial';receiptCtx.fillText('DAILY WEATHER',192,72);receiptCtx.font='900 42px Arial Narrow,Arial';receiptCtx.fillText(city.toUpperCase(),192,112);receiptCtx.font='900 92px Arial Narrow,Arial';receiptCtx.fillText(temperature+'°',192,215);receiptCtx.lineWidth=5;if(condition==='Sunny'){receiptCtx.beginPath();receiptCtx.arc(192,292,35,0,Math.PI*2);receiptCtx.stroke();for(let i=0;i<8;i++){const a=i*Math.PI/4;receiptCtx.beginPath();receiptCtx.moveTo(192+51*Math.cos(a),292+51*Math.sin(a));receiptCtx.lineTo(192+68*Math.cos(a),292+68*Math.sin(a));receiptCtx.stroke()}}else{receiptCtx.beginPath();receiptCtx.arc(165,286,33,Math.PI,Math.PI*2);receiptCtx.arc(207,276,44,Math.PI,Math.PI*2);receiptCtx.lineTo(250,320);receiptCtx.lineTo(133,320);receiptCtx.closePath();receiptCtx.stroke();if(condition==='Rainy')for(let x=160;x<=224;x+=32){receiptCtx.beginPath();receiptCtx.moveTo(x,335);receiptCtx.lineTo(x-8,352);receiptCtx.stroke()}}receiptCtx.font='900 30px Arial Narrow,Arial';receiptCtx.fillText(condition.toUpperCase(),192,398);archiveFooter('BERG CLOUD PUBLICATION · MANUAL DATA RECREATION')}
function drawButterfly(){receiptCtx.save();receiptCtx.translate(192,275);receiptCtx.lineWidth=3;for(const side of[-1,1]){receiptCtx.save();receiptCtx.scale(side,1);receiptCtx.beginPath();receiptCtx.moveTo(8,-12);receiptCtx.bezierCurveTo(50,-105,145,-98,112,4);receiptCtx.bezierCurveTo(98,60,50,70,8,20);receiptCtx.stroke();receiptCtx.beginPath();receiptCtx.moveTo(8,8);receiptCtx.bezierCurveTo(75,38,95,110,20,92);receiptCtx.bezierCurveTo(-2,65,2,30,8,8);receiptCtx.stroke();receiptCtx.beginPath();receiptCtx.arc(70,-25,18,0,Math.PI*2);receiptCtx.stroke();receiptCtx.restore()}receiptCtx.fillRect(-5,-52,10,118);receiptCtx.beginPath();receiptCtx.moveTo(-2,-50);receiptCtx.quadraticCurveTo(-35,-82,-48,-88);receiptCtx.moveTo(2,-50);receiptCtx.quadraticCurveTo(35,-82,48,-88);receiptCtx.stroke();receiptCtx.restore()}
function renderButterflies(){const name=$('#butterfly-name')?.value||'Peacock',[latin,fact]=BUTTERFLIES[name];prepareCanvas(620);receiptCtx.textAlign='center';receiptCtx.font='900 38px Arial Narrow,Arial';receiptCtx.fillText('BRITISH BUTTERFLIES',192,85);receiptCtx.font='900 28px Arial Narrow,Arial';receiptCtx.fillText(name.toUpperCase(),192,125);receiptCtx.font='italic 15px Georgia';receiptCtx.fillText(latin,192,149);drawButterfly();receiptCtx.font='17px Georgia';let y=470;for(const line of wrapLines(receiptCtx,fact,316)){receiptCtx.fillText(line,192,y);y+=23}archiveFooter()}
function renderFruit(){const name=$('#fruit-name')?.value||'Pomegranate',[latin,fact]=FRUITS[name];prepareCanvas(590);receiptCtx.textAlign='center';receiptCtx.font='900 35px Arial Narrow,Arial';receiptCtx.fillText('FRUIT',192,82);receiptCtx.font='11px Arial';receiptCtx.fillText('EDIBLE, INEDIBLE, INCREDIBLE',192,103);receiptCtx.lineWidth=3;receiptCtx.beginPath();receiptCtx.arc(192,274,105,0,Math.PI*2);receiptCtx.stroke();const rnd=seededRandom(name.length*927);for(let i=0;i<34;i++){const a=rnd()*Math.PI*2,r=Math.sqrt(rnd())*82,x=192+Math.cos(a)*r,y=274+Math.sin(a)*r;receiptCtx.beginPath();receiptCtx.ellipse(x,y,5,8,a,0,Math.PI*2);receiptCtx.stroke()}receiptCtx.font='900 27px Arial Narrow,Arial';receiptCtx.fillText(name.toUpperCase(),192,414);receiptCtx.font='italic 14px Georgia';receiptCtx.fillText(latin,192,437);receiptCtx.font='16px Georgia';let y=474;for(const line of wrapLines(receiptCtx,fact,320)){receiptCtx.fillText(line,192,y);y+=22}archiveFooter()}
function renderPollen(){const name=$('#pollen-name')?.value||'Sunflower',[latin,fact]=POLLEN[name];prepareCanvas(590);receiptCtx.textAlign='center';receiptCtx.font='900 40px Arial Narrow,Arial';receiptCtx.fillText('POLLEN',192,82);receiptCtx.font='11px Arial';receiptCtx.fillText('THE HIDDEN SEXUALITY OF FLOWERS',192,104);receiptCtx.lineWidth=3;receiptCtx.beginPath();receiptCtx.arc(192,268,112,0,Math.PI*2);receiptCtx.stroke();const rnd=seededRandom(name.length*811);for(let i=0;i<56;i++){const a=rnd()*Math.PI*2,r=Math.sqrt(rnd())*94;receiptCtx.beginPath();receiptCtx.arc(192+Math.cos(a)*r,268+Math.sin(a)*r,2+rnd()*4,0,Math.PI*2);receiptCtx.stroke()}for(let i=0;i<28;i++){const a=i*Math.PI/14;receiptCtx.beginPath();receiptCtx.moveTo(192+100*Math.cos(a),268+100*Math.sin(a));receiptCtx.lineTo(192+121*Math.cos(a),268+121*Math.sin(a));receiptCtx.stroke()}receiptCtx.font='900 27px Arial Narrow,Arial';receiptCtx.fillText(name.toUpperCase(),192,425);receiptCtx.font='italic 14px Georgia';receiptCtx.fillText(latin,192,447);receiptCtx.font='16px Georgia';let y=480;for(const line of wrapLines(receiptCtx,fact,320)){receiptCtx.fillText(line,192,y);y+=22}archiveFooter()}
function renderExploringType(){const character=($('#type-character')?.value||'R').slice(0,1).toUpperCase();prepareCanvas(560);receiptCtx.textAlign='center';receiptCtx.font='900 35px Arial Narrow,Arial';receiptCtx.fillText('EXPLORING TYPE',192,83);receiptCtx.font='900 250px Georgia';receiptCtx.fillText(character,192,330);receiptCtx.font='700 11px Arial';receiptCtx.textAlign='left';receiptCtx.fillText('CAP HEIGHT',28,153);receiptCtx.fillText('BASELINE',285,360);receiptCtx.setLineDash([4,3]);for(const y of[158,350]){receiptCtx.beginPath();receiptCtx.moveTo(25,y);receiptCtx.lineTo(359,y);receiptCtx.stroke()}receiptCtx.setLineDash([]);receiptCtx.textAlign='center';receiptCtx.font='16px Georgia';receiptCtx.fillText('LOOK CLOSELY. LETTERS ARE ENGINEERED.',192,430);archiveFooter()}
function renderGlyph(){const glyph=$('#glyph-name')?.value||'&',[name,fact]=GLYPHS[glyph];prepareCanvas(560);receiptCtx.textAlign='center';receiptCtx.font='900 38px Arial Narrow,Arial';receiptCtx.fillText('GLYPH',192,82);receiptCtx.font='900 235px Georgia';receiptCtx.fillText(glyph,192,315);receiptCtx.font='900 26px Arial Narrow,Arial';receiptCtx.fillText(name,192,375);receiptCtx.font='17px Georgia';let y=414;for(const line of wrapLines(receiptCtx,fact,318)){receiptCtx.fillText(line,192,y);y+=23}archiveFooter()}
function renderLunchbox(){const text=$('#lunchbox-note')?.value.trim()||'YOU ARE BRILLIANT!';prepareCanvas(500);receiptCtx.strokeStyle='#111';receiptCtx.lineWidth=4;receiptCtx.strokeRect(24,58,336,380);receiptCtx.textAlign='center';receiptCtx.font='900 28px Arial Narrow,Arial';receiptCtx.fillText('LUNCHBOX NOTE',192,98);receiptCtx.font='900 50px Arial Narrow,Arial';const lines=wrapLines(receiptCtx,text.toUpperCase(),292),lineHeight=51,start=235-lines.length*lineHeight/2;lines.forEach((line,index)=>receiptCtx.fillText(line,192,start+index*lineHeight));receiptCtx.font='30px Arial';receiptCtx.fillText('★  ♥  ★',192,397);archiveFooter()}
function renderTemplate(){const renderers={'daily-puzzle':renderDailyPuzzle,'maze-a-day':renderMaze,'daily-weather':renderWeather,'british-butterflies':renderButterflies,fruit:renderFruit,pollen:renderPollen,'exploring-type':renderExploringType,glyph:renderGlyph,'lunchbox-notes':renderLunchbox};(renderers[activeTemplate]||renderDailyPuzzle)()}
function renderReceipt(options={}){showPrintHeader=options.showPrintHeader!==false;if(activePanel==='draw')renderDrawing();else renderCompose();$('#receipt-length').textContent='≈ '+Math.ceil(receiptCanvas.height/8)+' mm receipt';updateSend()}

function selectPanel(panel){activePanel=panel;$$('.studio-tabs button').forEach(button=>button.classList.toggle('active',button.dataset.panel===panel));$$('.studio-panel').forEach(section=>{section.hidden=section.id!=='panel-'+panel;section.classList.toggle('active',!section.hidden)});scheduleRender()}
function templateFields(name){const archive='<p class="archive-note">Historical BERG title. This edition is an archive recreation; the original assets are unavailable.</p>';if(name==='daily-puzzle')return'<label class="wide">DIFFICULTY<select id="puzzle-level"><option>Easy</option><option selected>Medium</option><option>Hard</option></select></label>';if(name==='maze-a-day')return'<label class="wide">MAZE SIZE<select id="maze-size"><option>Small</option><option selected>Medium</option><option>Large</option></select></label><p class="archive-note">Recovered original Maze-A-Day artwork and algorithm, MIT licensed.</p>';if(name==='daily-weather')return'<label>CITY<input id="weather-city" maxlength="30" value="Bologna"></label><label>TEMPERATURE<input id="weather-temp" type="number" min="-50" max="60" value="18"></label><label class="wide">CONDITION<select id="weather-condition"><option>Cloudy</option><option>Sunny</option><option>Rainy</option></select></label>';if(name==='british-butterflies')return'<label class="wide">SPECIES<select id="butterfly-name">'+Object.keys(BUTTERFLIES).map(name=>'<option>'+name+'</option>').join('')+'</select></label>'+archive;if(name==='fruit')return'<label class="wide">SPECIMEN<select id="fruit-name">'+Object.keys(FRUITS).map(name=>'<option>'+name+'</option>').join('')+'</select></label>'+archive;if(name==='pollen')return'<label class="wide">SPECIMEN<select id="pollen-name">'+Object.keys(POLLEN).map(name=>'<option>'+name+'</option>').join('')+'</select></label>'+archive;if(name==='exploring-type')return'<label class="wide">CHARACTER<input id="type-character" maxlength="1" value="R"></label>'+archive;if(name==='glyph')return'<label class="wide">GLYPH<select id="glyph-name">'+Object.keys(GLYPHS).map(name=>'<option>'+name+'</option>').join('')+'</select></label>'+archive;if(name==='lunchbox-notes')return'<label class="wide">NOTE<input id="lunchbox-note" maxlength="100" value="You are brilliant!"></label>';return'<p class="archive-note">Unknown publication. Reload the page to update the catalogue.</p>'}

async function checkPrinter(){let url;try{url=endpoint()}catch(error){setNotice('error',errorText(error,'connect'),'×');return}const connect=$('#connect');connect.disabled=true;$('#refresh-status').disabled=true;connect.textContent='…';setNotice('sending','Looking for your Little Printer…','⌛');try{const response=await fetch(url,{method:'GET',mode:'cors',cache:'no-store',headers:{Accept:'application/json'}});if(response.status===404)throw new Error('not-found');if(!response.ok)throw new Error('HTTP '+response.status);const info=await response.json();if(!info?.name||!info?.status)throw new Error('invalid-response');printerConnected=true;$('#printer-name').textContent=info.name;const safeStatus=String(info.status).replace(/[^a-z-]/gi,'');$('#printer-info').innerHTML='<span class="dot '+safeStatus+'"></span>'+info.status+' · @'+String(info.owner||'unknown').replace(/[<>&"']/g,'')+' · checked now';setNotice(info.status==='online'?'sent':'error',info.status==='online'?'Your printer is online and ready.':'Your printer is currently offline.',info.status==='online'?'✓':'×')}catch(error){printerConnected=false;setNotice('error',errorText(error,'connect'),'×')}finally{connect.disabled=false;$('#refresh-status').disabled=false;connect.textContent='CONNECT'}}
function canvasBlob(){return new Promise((resolve,reject)=>receiptCanvas.toBlob(blob=>blob?resolve(blob):reject(new Error('render')),'image/png'))}
async function sendReceipt(){if(!senderInput.value.trim()){setNotice('error','Enter your name before sending.','×');return}if(!hasPrintableContent()){setNotice('error','Create something to print first.','×');return}let url;try{url=new URL(endpoint());url.searchParams.set('from',senderInput.value.trim())}catch(error){setNotice('error','Connect a valid Print Key first.','×');return}sendButton.disabled=true;setNotice('sending','Sending the exact thermal receipt…','⌛');try{renderReceipt({showPrintHeader:false});const blob=await canvasBlob();renderReceipt();const response=await fetch(url.toString(),{method:'POST',mode:'cors',cache:'no-store',headers:{'Content-Type':'image/png',Accept:'application/json'},body:blob}),result=await response.json().catch(()=>null);if(response.status===504||result?.status==='failed-offline')throw new Error('offline');if(response.status===404)throw new Error('not-found');if(!response.ok||result?.status!=='sent')throw new Error('HTTP '+response.status);setNotice('sent','Receipt sent to Little Printer!','✓');setTimeout(checkPrinter,800)}catch(error){setNotice('error',errorText(error,'send'),'×')}finally{renderReceipt();updateSend()}}

function scheduledJobs(){try{return JSON.parse(localStorage.getItem('lp-scheduled-jobs')||'[]')}catch{return[]}}
function renderJobs(){const jobs=scheduledJobs(),list=$('#scheduled-list');list.innerHTML=jobs.length?jobs.map(job=>'<div class="scheduled-item"><span><b>'+new Date(job.executeAt).toLocaleString()+'</b><br>'+job.kind+' · waiting for server connector</span><button type="button" data-delete-job="'+job.id+'">DELETE</button></div>').join(''):'<div class="scheduled-item"><span>No scheduled prints.</span></div>';list.querySelectorAll('[data-delete-job]').forEach(button=>button.addEventListener('click',()=>{localStorage.setItem('lp-scheduled-jobs',JSON.stringify(scheduledJobs().filter(job=>job.id!==button.dataset.deleteJob)));renderJobs()}))}
async function saveSchedule(){const executeAt=$('#schedule-time').value;if(!executeAt||new Date(executeAt)<=new Date()){setNotice('error','Choose a future date and time.','×');return}if(!senderInput.value.trim()||!hasPrintableContent()){setNotice('error','Add your name and printable content first.','×');return}const jobs=scheduledJobs();if(jobs.length>=8){setNotice('error','The local queue can contain up to 8 prints.','×');return}renderReceipt({showPrintHeader:false});const receiptPng=receiptCanvas.toDataURL('image/png');renderReceipt();jobs.push({version:1,id:String(Date.now()),executeAt:new Date(executeAt).toISOString(),createdAt:new Date().toISOString(),sender:senderInput.value.trim(),kind:activePanel,receiptPng,requiresServerConnector:true});try{localStorage.setItem('lp-scheduled-jobs',JSON.stringify(jobs));renderJobs();setNotice('sent','Print saved in the local schedule. It will be activated when the server connector is added.','✓')}catch{setNotice('error','This receipt is too large for local scheduling. Remove the image and try again.','×')}}

function setupDrawing(){drawingCtx.fillStyle='#fff';drawingCtx.fillRect(0,0,384,300);drawingCtx.strokeStyle='#111';drawingCtx.lineCap='round';drawingCtx.lineJoin='round';let drawing=false,last=null;const point=event=>{const rect=drawingCanvas.getBoundingClientRect(),touch=event.touches?.[0];return{x:((touch?.clientX??event.clientX)-rect.left)*(384/rect.width),y:((touch?.clientY??event.clientY)-rect.top)*(300/rect.height)}};const start=event=>{event.preventDefault();drawing=true;last=point(event)};const move=event=>{if(!drawing)return;event.preventDefault();const next=point(event);drawingCtx.lineWidth=Number($('#brush-size').value);drawingCtx.beginPath();drawingCtx.moveTo(last.x,last.y);drawingCtx.lineTo(next.x,next.y);drawingCtx.stroke();last=next;drawingUsed=true;scheduleRender()};const end=()=>{drawing=false;last=null};drawingCanvas.addEventListener('pointerdown',start);drawingCanvas.addEventListener('pointermove',move);window.addEventListener('pointerup',end);$('#clear-drawing').addEventListener('click',()=>{drawingCtx.fillStyle='#fff';drawingCtx.fillRect(0,0,384,300);drawingUsed=false;scheduleRender()})}

$('#reveal').addEventListener('click',event=>{const show=keyInput.type==='password';keyInput.type=show?'url':'password';event.currentTarget.textContent=show?'HIDE':'SHOW'});
$('#connect').addEventListener('click',checkPrinter);$('#refresh-status').addEventListener('click',checkPrinter);
keyInput.addEventListener('input',()=>{printerConnected=false;$('#printer-name').textContent='Connect a printer';$('#printer-info').textContent='Enter your Nord Projects Print Key';setNotice('','Connect with a Print Key, create a receipt, then send it.')});
senderInput.addEventListener('input',scheduleRender);titleInput.addEventListener('input',scheduleRender);messageInput.addEventListener('input',()=>{const chars=messageInput.value.length,lines=messageInput.value?messageInput.value.split(/\n/).reduce((sum,line)=>sum+Math.max(1,Math.ceil(line.length/38)),0):0;$('#counter').textContent=chars+'/800 characters';$('#line-count').textContent=lines+' estimated '+(lines===1?'line':'lines');scheduleRender()});
$$('.studio-tabs button').forEach(button=>button.addEventListener('click',()=>selectPanel(button.dataset.panel)));
imageInput.addEventListener('change',()=>{const file=imageInput.files?.[0];if(sourceImageUrl)URL.revokeObjectURL(sourceImageUrl);sourceImage=null;sourceImageUrl='';if(!file){scheduleRender();return}if(!['image/png','image/jpeg','image/gif'].includes(file.type)||file.size>MAX_IMAGE_BYTES){imageInput.value='';setNotice('error',file.size>MAX_IMAGE_BYTES?'The image must be smaller than 10 MB.':'Choose a PNG, JPEG or GIF image.','×');return}sourceImageUrl=URL.createObjectURL(file);const image=new Image();image.onload=()=>{sourceImage=image;$('#image-file-name').textContent=file.name+' · '+image.naturalWidth+'×'+image.naturalHeight;$('#remove-image').hidden=false;setNotice('','Full photo added without cropping. The thermal receipt expands to its complete length.');scheduleRender()};image.src=sourceImageUrl});
$('#remove-image').addEventListener('click',()=>{if(sourceImageUrl)URL.revokeObjectURL(sourceImageUrl);sourceImage=null;sourceImageUrl='';imageInput.value='';$('#image-file-name').textContent='＋ Add photo · long images supported';$('#remove-image').hidden=true;scheduleRender()});$('#dither-mode').addEventListener('change',scheduleRender);
sendButton.addEventListener('click',sendReceipt);$('#schedule-open').addEventListener('click',()=>{$('#scheduler').hidden=!$('#scheduler').hidden;renderJobs()});$('#schedule-save').addEventListener('click',saveSchedule);
setupDrawing();selectPanel('compose');const defaultSchedule=new Date(Date.now()+3600000);defaultSchedule.setMinutes(defaultSchedule.getMinutes()-defaultSchedule.getTimezoneOffset());$('#schedule-time').min=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);$('#schedule-time').value=defaultSchedule.toISOString().slice(0,16);document.fonts?.ready.then(renderReceipt);renderReceipt();renderJobs();
